name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - name: Wait on tests
       uses: lewagon/wait-on-check-action@v0.2
       with:
         ref: ${{ github.ref }}
         check-name: test
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         wait-interval: 5
     - name: Update Deployment Status
       run: |
         curl \
         -X POST \
         -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/repos/${{github.repository}}/deployments \
         -d '{"ref":"${{ github.sha }}", "required_contexts": []}'